/*
 * Peter Horne-Deus
 * The is a program to calculate the ronding error when squaring / square rooting
 * RoudningError.java
 * Febuary 19, 2019
 */


package roundingerror;

/**
 *
 * @author pehor9164
 */
public class RoundingError extends javax.swing.JFrame {

    /**
     * Creates new form rounding
     */
    public RoundingError() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numberLable = new javax.swing.JLabel();
        numberTxtFeild = new javax.swing.JTextField();
        continueBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numberLable.setText("Enter A Number Of Your Choice:");
        jPanel1.add(numberLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        numberTxtFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTxtFeildActionPerformed(evt);
            }
        });
        jPanel1.add(numberTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, -1));

        continueBtn.setText("Continue");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });
        jPanel1.add(continueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberTxtFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTxtFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTxtFeildActionPerformed
    
    /**
     * This method finds the rounding error of squaring and square rooting when button is clicked
     * 
     */
    
    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
        //Variables
        double num = Double.parseDouble(numberTxtFeild.getText());
        double square = Math.sqrt(num);
        double roundOff = square - num;
        
        //Calculations
        square = Math.pow(square, 2);
        
        //Printing the results of the math calculated above
        System.out.println(num + " squared  and square rootd is: " + square);
        System.out.println("The difference is " + roundOff);
        
        //Exits the program 
        System.exit(0);
    }//GEN-LAST:event_continueBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoundingError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoundingError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoundingError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoundingError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoundingError().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton continueBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numberLable;
    private javax.swing.JTextField numberTxtFeild;
    // End of variables declaration//GEN-END:variables
}
